BEGIN TRANSACTION;
DROP TABLE IF EXISTS "OtpKeys";
CREATE TABLE IF NOT EXISTS "OtpKeys" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Description"	TEXT NOT NULL UNIQUE,
	"Base32SecretKey"	TEXT NOT NULL
);
DROP TABLE IF EXISTS "Settings";
CREATE TABLE IF NOT EXISTS "Settings" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Key"	TEXT NOT NULL UNIQUE,
	"Value"	TEXT NOT NULL
);
INSERT INTO "Settings" VALUES (1,'DB_VERSION','2');
COMMIT;
